### ISSUE TITLE
PuTTY 0.69?

### ISSUE THREAD

**Issue by mattpwhite** [adamel/putty#2]
Hello,
I see that you have an 0.68 branch, but never created a release of that, so it wasn't clear what state it might be in, and now PuTTY 0.69 is is available.

I'm curious about your plans for maintaining this fork going forward and when/whether you anticipate merging the changes from the upstream PuTTY 0.69.  This isn't any sort of complaint, just a question about your plans.

And thanks for your work on this in general, it's been extremely helpful.

**Comment by adamel** [comment]
The reason 0.68 was not released is that my code signing certificate expired, and to get a new one I apparently need to get a HSM (Hardware Security Module) to store the private key. That is unfortunately still not resolved, but I have updated the sources to 0.69, and also made pre-release binaries signed with the old expired certificate (and my gpg key as usual) available at https://marcussundberg.com/putty/0.69-0.9/

**Comment by mattpwhite** [comment]
Thanks, much appreciated.
